# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: .github # https://github.com/rogerluan/.github

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: FeatureConfig

  # A short description of the repository that will show up on GitHub
  description: ⚙️ An extensible feature flag and remote config service.

  # A URL with more information about the repository
  homepage: https://github.com/rogerluan/FeatureConfig

  # A comma-separated list of topics to set on the repository
  topics: swift, spm, ios
